# URL базы данных (логин/пароль зависят от того, что ты укажешь при установке Postgres)
spring.datasource.url=jdbc:postgresql://localhost:5432/passmanager_db
spring.datasource.username=postgres
spring.datasource.password=QAE3PFL737

# Позволяет Spring Boot автоматически создавать таблицы на основе твоих Java-классов
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect